# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-19 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userinfo_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name2',
        ),
    ]
