# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-20 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_userinfo_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
